### ISSUE TITLE
Necesito que coloquen opcion para ubicacion en el login

### ISSUE THREAD

**Issue by rigby0115** [alexis-1729/RiverSafe#1]
todas las notas sobre esto o cualquier duda estan en los archivos de rios que modifique, cada uno en su respectivo lugar y mencionando que hace cada cosa y para que, instale geolocation de ionic para saber la ubicacion del usuario, agregue varias variables pero la importante es userLocation en rios-page.ts con esta verificaremos la ubicacion del usuario por lo que puso en el login y se usara para verificar que rios monitoreados estan cerca de el.
la funcionalidad de la pestaña de rios todavia esta incompleta ahora pero pronto la completare y estaria bien que me apoyaran en esto ya que no quiero modificar nada que no sea de mi area.

**Comment by alexis-1729** [comment]
lo que necesitas es un campo en el formulario donde se ingrese la ubicacion? 
por que en la base de datos dependiendo del rio existen campo estado, e informacion de latitud y longitud segun sea el rio, 
o la intencion de la ubicacion es dependiendo donde se encuentre el usuario mostrar los rios cercanos?
  
o una venta para dar  permiso y poder usar la localizacion

**Comment by alexis-1729** [comment]
analizando geolocation de ionic se inicia a la hora de cargar la pagina rios por lo que se obtiene la latitud y longitud una vez se de el permiso ademas de que el premiso lo genera y gestiona automaticamente, por lo que no es necesario añadir como tal una opcion en el login, auque en la opcion de registro se pide llenar un campo del rio en cuestion que desea llenar, por lo que esa parte ya esta cubierta

**Comment by rigby0115** [comment]
ah va pues, tenia esa duda de como funcionaba concretamente, no hace falta añadir otra cosa en esa parte? tipo para el permiso cuando salga el anuncio de permitir ubicacion o algo?

**Comment by alexis-1729** [comment]
la ventana de confirmacion es automática, aunque se puede personalizar pero por el momento se queda asi
